import { Component } from '@angular/core';
import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';

// Fonts registrieren
(pdfMake as any).vfs = (pdfFonts as any).vfs;

@Component({
  selector: 'app-page2',
  standalone: true,
  imports: [],
  templateUrl: './page2.html',
  styleUrl: './page2.css'
})
export class Page2 {

  generatePDF() {
    let docDefinition = {
      content:   [
        this.text
      ]
  };

    pdfMake.createPdf(docDefinition).download('sample.pdf');
  }
  
 text: string = 'This document is a sample PDF document generated by pdfMake in Angular';
  
}